"""empty message

Revision ID: 42551d29dace
Revises: 1bae5acfb326
Create Date: 2021-03-28 23:45:45.972252

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '42551d29dace'
down_revision = '1bae5acfb326'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('post', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('post', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
